version: "3"

services:
  chatbot:
    container_name: backend_chatbot
    build: ./
    command: sh -c "python3 ./manage.py migrate &&
      python3 ./manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
    volumes:
        - .:/app
    restart: always
