# Generated by Django 4.1.13 on 2024-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examples',
            name='example',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
